name: lila
channels:
  - conda-forge
dependencies:
  - python =3.10 # different from notebook version
  - pip
  - conda
  - mamba
  - notebook
  - fiona
  - shapely
  - rasterio
  - pyproj
  - pandas
  - geopandas
  - matplotlib-scalebar